### ISSUE TITLE
sometines steam is installed via snap, could be nice to autodetect the directory where game is.

### ISSUE THREAD

**Issue by felisucoibi** [ardba/proton_aoe2de_mpfix#1]
sometines steam is installed via snap, could be nice to autodetect the directory where game is.

example
cp ucrtbase.dll  /home/felisuco/.steam/debian-installation/steamapps/compatdata/1493710/pfx/drive_c/windows/system32/ # This changes sometimes, depending on proton version?

**Comment by ardba** [comment]
Would it work if we make the steam install directory into an argument you could give the script? 
if not set it would default to what it is today

**Comment by agners** [comment]
Similarly, using Steam from Flatpak stores data at a different location. I was able to use the script using:

```
STEAM_LOCATION=/home/$USER/.var/app/com.valvesoftware.Steam/data
```

There was already a `ucrtbase.dll` with different md5sum. Replacing it worked.

However, I am still unable to join Multiplayer games. The game is claiming I am "Offline", "Reconnect to Multiplayer Services" only shows an error "Cannot connect to Steam. Please check your internet connection." The same setup worked some weeks ago, I am a bit lost what the problem is.

**Comment by RochaLAJ** [comment]
If you have the game installed on a different partition, the script will fail too and you need to replace manually. 

For example
```
ls $SYSTEM32_LOCATION
/home/rochalaj/.local/share/Steam/steamapps/compatdata/813780/pfx/drive_c/windows/system32: No such file or directory (os error 2).
```
Because my game is under
`/mnt/HD/SteamLibrary/steamapps/compatdata/813780/pfx/drive_c/windows/system32`

**Comment by ardba** [comment]
Done in [here](https://github.com/ardba/proton_aoe2de_mpfix/commit/8f91fe7ab9d38512e90cd614930b21b5cdbdf8ab)
