### ISSUE TITLE
Wrong steam ID? 1493710 -> 813780

### ISSUE THREAD

**Issue by RlndVt** [ardba/proton_aoe2de_mpfix#2]
For me changing the .dll in the '1493710' had no effect; I had to change the .dll in '813780'.

Thanks to [this](https://www.protondb.com/app/813780#Q4zLG6ptWw) comment on protondb to point me in the right direction. (Totally unnecessary to run those commands with sudo.)

**Comment by ardba** [comment]
1493710: Proton Experimental
813780: Age of Empires II Definitive Edition

The id is also in the store url: https://store.steampowered.com/app/813780/Age_of_Empires_II_Definitive_Edition/

You can check this guide for when the steam app id is not known: 
https://steamcommunity.com/sharedfiles/filedetails/?id=637176687

I honestly don't know how to auto identify the proton version used by aoe. I was considering just making the aoe wineprefix directory into an optional argument in the script.

**Comment by RlndVt** [comment]
So depending on if you use the default Proton version the DLL in 813780 needs to be replaced; and if you switch to Proton Experimental you need to change the DLL in 1493710?

Which would be strange; on my laptop I selected Proton Experimental yet still only changed the DLL in 813780. On my Steam Deck I don't specify a version of Proton and again only changed the DLL in 813780.

**Comment by ardba** [comment]
> So depending on if you use the default Proton version the DLL in 813780 needs to be replaced; and if you switch to Proton Experimental you need to change the DLL in 1493710?

I thought it was like that but I checked it out, I was wrong. Steam makes a symlink in `~/.local/share/Steam/steamapps/compatdata/813780/pfx/drive_c/windows/system32/ucrtbase.dll` pointing to the `ucrtbase.dll` of whichever proton version you're using. In my case, because it was proton experimental  I didn't notice the issue. 

But you are 100% right, it should be using 813780, also this way we don't change the dll for any other game using that proton version that might be negatively affected. 

If you are super kind to push another commit in your pull request with this change I will approve it right away. Otherwise I'll take a look at this on Sunday
